//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// BOKODoroTimer.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BOKODOROTIMER_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDB_PNG_BK_ETC                  130
#define IDB_PNG_BK_MAIN                 131
#define IDB_PNG_BK_SUB                  132
#define IDB_PNG_ICON2                   133
#define IDR_TEXT_DIGITAL_FONT           135
#define IDR_TEXT_GOODDAY_FONT           136
#define IDB_PNG_BK_MAIN_GREEN           137
#define IDB_PNG_BK_MAIN_RED             138
#define IDB_PNG3                        139
#define IDB_PNG_BK_MAIN_YELLOW          139
#define IDD_DIALOG_TIMER_LIST           140
#define IDD_DIALOG_ADD_TIMER_NAME       142
#define IDD_DIALOG_TIMER_LIST_CTRL      145
#define IDD_DIALOG_SCROLL_BAR           149
#define IDB_PNG_NONE_SOUND              158
#define IDB_PNG_SOUND                   159
#define IDB_PNG1                        161
#define IDB_PNG_LIST                    161
#define IDR_WAVE_ALL_END                162
#define IDR_WAVE_REFRESH                163
#define IDR_WAVE_REFRESH_START          164
#define IDR_WAVE_REST                   165
#define IDR_WAVE_REST_START             166
#define IDR_WAVE_WORK                   167
#define IDR_WAVE7                       168
#define IDR_WAVE_WORK_START             168
#define IDC_STATIC_REPEAT               1000
#define IDC_STATIC_WORK_TIME            1001
#define IDC_STATIC_REST_TIME            1002
#define IDC_STATIC_REFRESH_TIME         1003
#define IDC_MFCBUTTON_START             1004
#define IDC_MFCBUTTON_STOP              1005
#define IDC_MFCBUTTON_RESET             1006
#define IDC_STATIC_STATE                1007
#define IDC_EDIT_STATE                  1008
#define IDC_RADIO_INFINITE              1009
#define IDC_RADIO_CUSTOM                1012
#define IDC_STATIC_WORK_REST_REPEAT_SET 1013
#define IDC_STATIC_ALL_REPEAT_SET       1014
#define IDC_EDIT_WORK_REST_REPEAT_SET   1015
#define IDC_EDIT_ALL_REPEAT_SET         1016
#define IDC_EDIT_WORK_HOUR1             1017
#define IDC_EDIT_WORK_HOUR2             1018
#define IDC_EDIT_WORK_MINUTE1           1019
#define IDC_EDIT_WORK_MINUTE2           1020
#define IDC_EDIT_WORK_SECOND1           1021
#define IDC_EDIT_WORK_SECOND2           1022
#define IDC_MFCBUTTON_WORK_HOUR_UP      1023
#define IDC_MFCBUTTON_WORK_HOUR_DOWN    1024
#define IDC_MFCBUTTON_WORK_MINUTE_UP    1025
#define IDC_MFCBUTTON_WORK_MINUTE_DOWN  1026
#define IDC_MFCBUTTON_WORK_SECOND_UP    1027
#define IDC_MFCBUTTON_WORK_SECOND_DOWN  1028
#define IDC_STATIC_HOUR                 1029
#define IDC_STATIC_WORK_HOUR            1029
#define IDC_STATIC_WORK_MINUTE          1030
#define IDC_STATIC_WORK_SECOND          1031
#define IDC_EDIT_REST_HOUR1             1032
#define IDC_EDIT_REST_HOUR2             1033
#define IDC_EDIT_REST_MINUTE1           1034
#define IDC_EDIT_REST_MINUTE2           1035
#define IDC_EDIT_REST_SECOND1           1036
#define IDC_EDIT_REST_SECOND2           1037
#define IDC_MFCBUTTON_REST_HOUR_UP      1038
#define IDC_MFCBUTTON_REST_HOUR_DOWN    1039
#define IDC_MFCBUTTON_REST_MINUTE_UP    1040
#define IDC_MFCBUTTON_REST_MINUTE_DOWN  1041
#define IDC_MFCBUTTON_REST_SECOND_UP    1042
#define IDC_MFCBUTTON6                  1043
#define IDC_MFCBUTTON_REST_SECOND_DOWN  1043
#define IDC_STATIC_REST_HOUR            1044
#define IDC_STATIC_REST_MINUTE          1045
#define IDC_STATIC_REST_SECOND          1046
#define IDC_EDIT_REFRESH_HOUR1          1047
#define IDC_EDIT_REFRESH_HOUR2          1048
#define IDC_EDIT_REFRESH_MINUTE1        1049
#define IDC_EDIT_REFRESH_MINUTE2        1050
#define IDC_EDIT_REFRESH_SECOND1        1051
#define IDC_EDIT_REFRESH_SECOND2        1052
#define IDC_MFCBUTTON_REFRESH_HOUR_UP   1053
#define IDC_MFCBUTTON_REFRESH_HOUR_DOWN 1054
#define IDC_MFCBUTTON_REFRESH_MINUTE_UP 1055
#define IDC_MFCBUTTON_REFRESH_MINUTE_DOWN 1056
#define IDC_MFCBUTTON_REFRESH_SECOND_UP 1057
#define IDC_MFCBUTTON7                  1058
#define IDC_MFCBUTTON_REFRESH_SECOND_DOWN 1058
#define IDC_STATIC_REFRESH_HOUR         1059
#define IDC_STATIC_REFRESH_MINUTE       1060
#define IDC_STATIC_REFRESH_SECOND       1061
#define IDC_MFCBUTTON_EXPAND_TIMER_LIST 1062
#define IDC_STATIC_GROUP_WORK           1063
#define IDC_STATIC_GROUP_REST           1064
#define IDC_STATIC_GROUP_REFRESH        1065
#define IDC_STATIC_GROUP_REPEAT         1066
#define IDC_MFCBUTTON_TIMER_SAVE        1067
#define IDC_EDIT_TIMER_NAME             1068
#define IDC_MFCBUTTON_SAVE_TIMER_NAME   1069
#define IDC_MFCBUTTON_CANCEL_TIMER_NAME 1070
#define IDC_STATIC_TIMER_NAME           1071
#define IDC_MFCBUTTON_TIMER_DELETE      1073
#define IDC_MFCBUTTON_TOP               1074
#define IDC_MFCBUTTON_BOTTOM            1075
#define IDC_MFCBUTTON_MIDDLE            1076
#define IDC_BUTTON_SOUND_SETTING        1077
#define IDC_BUTTON_NONE_SOUND_SETTING   1078

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
